name: Terraform Plan

on:
  pull_request:
     branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get OIDC Token
        id: oidc
        run: |
          token=$(curl -s -X POST "${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}" \
            -H "Accept: application/json; api-version=2.0" \
            -H "Authorization: bearer ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}" \
            --data-raw '{"audience":"api://AzureADTokenExchange"}' | jq -r '.value')
          echo "::add-mask::$token"
          echo "OIDC_TOKEN=$token" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_OIDC_TOKEN: ${{ steps.oidc.outputs.OIDC_TOKEN }}
          ARM_USE_OIDC: true
        
      - name: Terraform Plan
        run: terraform plan -var-file="env/dev.tfvars"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_OIDC_TOKEN: ${{ steps.oidc.outputs.OIDC_TOKEN }}
          ARM_USE_OIDC: true
